# Generated by Django 4.1 on 2022-08-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__last_name'], 'permissions': [('view_history', 'can view history')]},
        ),
    ]
